Used init scripts and logrotate scripts from upstream.

diff --git a/debian/shairport.init b/debian/shairport.init
--- a/debian/shairport.init
+++ b/debian/shairport.init
@@ -1,65 +1,124 @@
-#!/bin/sh
+#! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          shairport
-# Required-Start:    $remote_fs avahi
-# Required-Stop:     $remote_fs avahi
-# Should-Start:	     $syslog
-# Should-Stop:       $syslog
+# Required-Start:    $remote_fs
+# Required-Stop:     $remote_fs
+# Should-Start:      pulseaudio alsa-utils hostname avahi
+# Should-Stop:       pulseaudio alsa-utils hostname avahi
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Shairport AirTunes emulator daemon
-# Description:       Daemon that speaks the Apple RAOP protocol for
-#                    streaming music from Apple Macs, iPods, and iPhones
 ### END INIT INFO
 
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
-DESC="Shairport AirTunes emulator"
-NAME="shairport"
-DAEMON="/usr/bin/$NAME"
-SCRIPTNAME=/etc/init.d/$NAME
-SHAIRPORT_NAME="RaspberryPi"
-SHAIRPORT_OPTS="-d -P /var/run/shairport.pid"
+# Do not modify this file. Edit /etc/default/shairport instead !
 
-# Gracefully exit if the package has been removed.
-test -x $DAEMON || exit 0
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Shairport Airtunes emulator"
+NAME=shairport
+DAEMON=/usr/bin/shairport
 
+# Configuration defaults
+USER=shairport
+GROUP=nogroup
+LOGFILE=/var/log/$NAME.log
+ERRFILE=/var/log/$NAME.err
+PIDFILE=/var/run/$NAME.pid
+AP_NAME=$(hostname)
+NICE=0
+
+test -f /etc/default/shairport && . /etc/default/shairport
+
+DAEMON_ARGS="--daemon --pidfile $PIDFILE --log $LOGFILE"
+
+[ -z "$ERRFILE" ]     || DAEMON_ARGS="$DAEMON_ARGS --error $ERRFILE"
+[ -z "$AP_NAME" ]     || DAEMON_ARGS="$DAEMON_ARGS --name $AP_NAME"
+[ -z "$BUFFER_FILL" ] || DAEMON_ARGS="$DAEMON_ARGS -b $BUFFER_FILL"
+[ -z "$RUN_ONSTART" ]    || DAEMON_ARGS="$DAEMON_ARGS --on-start \"$RUN_ONSTART\""
+[ -z "$RUN_ONSTOP" ]     || DAEMON_ARGS="$DAEMON_ARGS --on-stop \"$RUN_ONSTOP\""
+[ -z "$OUTPUT" ]      || DAEMON_ARGS="$DAEMON_ARGS --output $OUTPUT"
+[ -z "$MDNS" ]        || DAEMON_ARGS="$DAEMON_ARGS --mdns $MDNS"
+[ -z "$OUTPUT_OPTS" ] || DAEMON_ARGS="$DAEMON_ARGS -- $OUTPUT_OPTS"
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || { echo "$NAME is not installed" >&2 ; exit 1; }
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
 . /lib/lsb/init-functions
 
-# Include shairport defaults if available.
-test -f /etc/default/shairport && . /etc/default/shairport
+do_start()
+{
+    # Let the daemon write to the pid/log/error files
+    touch $PIDFILE $LOGFILE $ERRFILE
+    chown root:$GROUP $PIDFILE $LOGFILE $ERRFILE
+    chmod 660 $PIDFILE $LOGFILE $ERRFILE
+
+    start-stop-daemon --start --quiet \
+        --pidfile $PIDFILE \
+        --exec $DAEMON \
+        --chuid $USER:$GROUP \
+        --nicelevel $NICE \
+        -- $DAEMON_ARGS
+}
+
+do_stop()
+{
+    start-stop-daemon --stop --quiet \
+        --pidfile $PIDFILE \
+        --exec $DAEMON \
+        --name $NAME \
+        --retry=TERM/10/KILL/5
+}
+
+do_reload()
+{
+    [ -f $PIDFILE ] && kill -HUP $(cat $PIDFILE) || return 1
+}
 
 case "$1" in
   start)
-        log_daemon_msg "Starting Shairport server" "shairport" || true
-        if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/shairport.pid --exec $DAEMON -- -a $SHAIRPORT_NAME $SHAIRPORT_OPTS; then
-            log_end_msg 0 || true
-        else
-            log_end_msg 1 || true
-        fi
-        ;;
+	log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+        log_end_msg $?
+	;;
   stop)
-        log_daemon_msg "Stopping Shairport server" "shairport" || true
-        if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/shairport.pid; then
-            log_end_msg 0 || true
-        else
-            log_end_msg 1 || true
-        fi
-        ;;
-  restart|reload|force-reload)
-        log_daemon_msg "Restarting Shairport server" "shairport" || true
-        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/shairport.pid
-        if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/shairport.pid --exec $DAEMON -- -a $SHAIRPORT_NAME $SHAIRPORT_OPTS; then
-            log_end_msg 0 || true
-        else
-            log_end_msg 1 || true
-        fi
+	log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+        log_end_msg $?
+	;;
+  reload)
+        log_daemon_msg "Reloading $DESC" "$NAME"
+        do_reload
+        log_end_msg $?
         ;;
   status)
-        status_of_proc -p /var/run/shairport.pid /usr/bin/shairport shairport && exit 0 || exit $?
-        ;;
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+  restart|force-reload)
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
   *)
-        log_action_msg "Usage: /etc/init.d/shairport {start|stop|restart|status}" || true
-        exit 1
+	echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
 exit 0
